#     Lazarus - A fork of Dodo, a graphical, hackable email client based on notmuch
#     Copyright (C) 2025 - Ruly Tafzil
#
# This file is part of Lazarus
#
# Lazarus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Lazarus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lazarus. If not, see <https://www.gnu.org/licenses/>.
"""Structural protocols used across panels and the controller.

``PanelApp`` is the interface panels rely on — satisfied by both
``Dodo`` (QApplication bootstrap) and ``AppController`` (which the
panels actually receive at runtime).  ``ThreadList`` and ``ThreadView``
narrow the current tab / preview pane to the method sets the global
keymap dispatches to, so controller dispatch is type-checked and
``isinstance`` narrowing is structural (``runtime_checkable``) instead
of the old ``hasattr`` chains that failed silently on typos.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal, Optional, Protocol, runtime_checkable, Union

if TYPE_CHECKING:
    from PyQt6.QtWidgets import QTabWidget

    from .mainwindow import MainWindow
    from .panel import Panel


class PanelApp(Protocol):
    """The app-level interface panels and keymaps call into.

    Both :class:`~lazarus.app.Dodo` and
    :class:`~lazarus.controller.AppController` satisfy this protocol.
    Both are ``QObject`` subclasses, so call sites that need a Qt parent
    can cast (see ``thread.py``).
    """

    main_window: "MainWindow"
    tabs: "QTabWidget"
    panel_history: list["Panel"]

    def show_help(self) -> None: ...
    def raise_panel(self, p: "Panel") -> None: ...
    def message(self, title: str, body: str) -> None: ...
    def status_message(self, message: str, kind: str = 'info',
                       duration: int = 3000) -> None: ...
    def navigate_list(self, direction: str) -> None: ...
    def mark_and_advance(self) -> None: ...
    def delegate_to_list(self, method: str, **kwargs: object) -> None: ...
    def delegate_to_thread(self, method: str, **kwargs: object) -> None: ...
    def toggle_tag_hotkey(self, key: str) -> None: ...
    def add_panel(self, p: "Panel", focus: bool = True) -> None: ...
    def next_panel(self) -> None: ...
    def previous_panel(self) -> None: ...
    def close_panel(self, to_close: Union[int, "Panel", None] = None) -> None: ...
    def open_search(self, query: str, keep_open: bool = False) -> None: ...
    def open_thread(self, thread_id: str, query: str) -> None: ...
    def open_compose(self, mode: str = '', msg: Optional[dict] = None) -> None: ...
    def open_tags(self, keep_open: bool = False) -> None: ...
    def search_bar(self) -> None: ...
    def edit_search_query(self) -> None: ...
    def tag_bar(self, mode: Literal['tag', 'tag marked'] = 'tag') -> None: ...
    def sync_mail(self, quiet: bool = True) -> None: ...
    def apply_filter_rules(self) -> None: ...
    def expunge_trash(self) -> None: ...
    def num_panels(self) -> int: ...
    def refresh_tab_titles(self) -> None: ...
    def refresh_panels(self) -> None: ...
    def update_single_thread(self, thread_id: str,
                             msg_id: Optional[str] = None) -> None: ...
    def prompt_quit(self) -> None: ...


@runtime_checkable
class ThreadList(Protocol):
    """A tab widget showing a searchable thread list (e.g. SearchPanel)."""

    def next_thread(self, unread: bool = False) -> None: ...
    def previous_thread(self, unread: bool = False) -> None: ...
    def first_thread(self) -> None: ...
    def last_thread(self) -> None: ...
    def toggle_thread_tag(self, tag: str) -> None: ...
    def open_current_thread(self) -> None: ...
    def prev_page(self) -> None: ...
    def next_page(self) -> None: ...
    def archive_thread(self) -> None: ...
    def delete_thread(self) -> None: ...
    def restore_thread_from_trash(self) -> None: ...
    def archive_to_local(self) -> None: ...


@runtime_checkable
class ThreadView(Protocol):
    """The thread preview pane (e.g. ThreadPanel)."""

    def next_message(self) -> None: ...
    def previous_message(self) -> None: ...
    def scroll_message(
            self,
            lines: Optional[int] = None,
            pages: Optional[Union[float, int]] = None,
            pos: Optional[str] = None) -> None: ...
    def toggle_html(self) -> None: ...
    def toggle_remote_content(self) -> None: ...
    def toggle_list_mode(self) -> None: ...
    def reply(self, to_all: bool = True) -> None: ...
    def forward(self) -> None: ...
    def open_attachments(self) -> None: ...
    def tag_message(self, tag_expr: str) -> None: ...
    def update_thread(self, thread_id: str,
                      msg_id: Optional[str] = None) -> None: ...
    def title(self) -> str: ...
    def refresh(self) -> None: ...
    def before_close(self) -> bool: ...


# Method names each protocol exposes, for fail-fast validation of the
# string-based dispatch helpers (delegate_to_list / delegate_to_thread).
LIST_METHODS = frozenset((
    'next_thread', 'previous_thread', 'first_thread', 'last_thread',
    'toggle_thread_tag', 'open_current_thread', 'prev_page', 'next_page',
    'archive_thread', 'delete_thread', 'restore_thread_from_trash',
    'archive_to_local',
))

THREAD_METHODS = frozenset((
    'next_message', 'previous_message', 'scroll_message', 'toggle_html',
    'toggle_remote_content', 'toggle_list_mode', 'reply', 'forward',
    'open_attachments', 'tag_message', 'update_thread',
))
